### ISSUE TITLE
vCard minimal content required

### ISSUE THREAD

**Issue by arturhefczyc** [tigase/halcyon#10]
We require the following, minimum content supported in vCards for contacts:

* email
* firstName
* lastName
* role
* phone
* birthday date
* timezone
* street address
* country address
* city address
* postal code address
* region (maybe not mandatory)

As for the firstName/lastName I am not sure how related to this is currently supported `structuredName` and `formattedName`. Maybe this would be enough and we do not need first/last names. I am not sure at this point.

**Comment by bmalkow** [comment]
What kind of "region" do you mean?

**Comment by bmalkow** [comment]
There is already 'VCardModule' in Halcyon. You can use it to retrieve vcards. It doesn't have all field you asked for. 
I'm adding those fields, but I found problem, because data structures and helper methods was prepared for getting information from vcards, not for setting. So I'm working on VCardBuilder.

**Comment by hantu85** [comment]
But we not always want to change a while vcard, we may want to "update" parts of it by editing only some fields. Would it mean that with `builder` we would have to `re-set` all the fields to achieve that?

**Comment by arturhefczyc** [comment]
Thank you Bartek.
First, we need support to retrieve vcard and all required fields.

Setting vcard will also be needed but at later time.

**Comment by bmalkow** [comment]
Implemented. Documentation is [here](https://github.com/tigase/halcyon/blob/master/halcyon-docs/src/docs/asciidoc/text/modules/VCard4Module.asciidoc).

**Comment by arturhefczyc** [comment]
Thank you. I can use the current implementation and write the code as in examples. 

However, I am a bit confused as to which API to use. From initial examples and documentation the library seems to prefer convention to register handlers for a specific event. Then send a request and expect a call back on the registered handler.

The examples linked above show a bit different way to provide handler directly in the request call. Why is this difference? Which way is preferred or recommended? Does the VCardModule allow for registering the handler for vCard requests?

**Comment by hantu85** [comment]
Handlers registration is for accepting events triggered by incoming stanzas, ie. incoming `<message/>`s.
Providing handler directly in the request call is for "handling" response on stanza which was sent by this client, ie. for request-response mechanism used by `<iq/>`.

**Comment by arturhefczyc** [comment]
Hm, ok, this makes sense. Thank you for explanation.

**Comment by arturhefczyc** [comment]
Do I need to register handler for vCard module at all?

**Comment by hantu85** [comment]
Do you need to? No, but you should. VCard4 is PEP-based, so you may receive PubSub notification that new VCard was published and for that registered handler will be called.

**Comment by arturhefczyc** [comment]
Ok, understand. Thanks a lot.

**Comment by arturhefczyc** [comment]
All works as expected.
