### ISSUE TITLE
Logs on all levels contains huge chunks of data

### ISSUE THREAD

**Issue by arturhefczyc** [tigase/halcyon#8]
Right now logs on levels from FINEST to FINE contain entire content of stanzas received. Especially for packets like avatar data it makes it very difficult to read and analyze logs which tend to rapidly grow.

It would be much more useful to limit such a high verbosity to the highest log level - FINEST. Any level below that should only contain most critical parts of the stanza. Maybe just the first level of the XML or maybe 2 levels deep. Just to avoid huge chunks of data in the log files.

**Comment by bmalkow** [comment]
Done. You can check it.

**Comment by arturhefczyc** [comment]
Thank you.
